CREATE DATABASE SoftTrade

/*
	В проекте используется следующий ConnectionString:
		Data Source=.\SQLEXPRESS;Initial Catalog=SoftTrade;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework
		
	После создания бд накатить миграции EnitityFramework Core
*/

DELETE FROM Managers;
DELETE FROM Products;
DELETE FROM Clients;
DELETE FROM ClientProduct;

--#region Добавление менеджеров
INSERT INTO [Managers] ([Name]) VALUES (N'Кузьмин Лаврентий Артемович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Фёдоров Леонтий Вячеславович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Костин Аверкий Антонович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Беспалов Георгий Геннадьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Ермаков Гавриил Алексеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Овчинников Аверьян Степанович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Титов Болеслав Вадимович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Меркушев Мстислав Григорьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Воронов Аркадий Мартынович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Миронов Осип Еремеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Воронцов Федор Христофорович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Воробьёв Егор Иосифович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Маслов Вольдемар Феликсович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Дроздов Лев Гордеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Зайцев Лазарь Христофорович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Беспалов Касьян Кимович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Шилов Устин Васильевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Никифоров Илья Геннадьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Дорофеев Станислав Витальевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Богданов Игорь Артёмович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Беляев Нисон Платонович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Горшков Станислав Лукьянович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Яковлев Лаврентий Созонович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Попов Филипп Всеволодович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Рыбаков Казимир Ростиславович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Архипов Остап Алексеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Кулагин Моисей Семёнович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Григорьев Аким Давидович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Романов Карл Викторович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Самсонов Кассиан Богуславович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Лаврентьев Юлий Леонидович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Коновалов Гордий Аркадьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Фёдоров Николай Лаврентьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Андреев Артур Денисович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Туров Пантелей Авдеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Лаврентьев Людвиг Васильевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Комиссаров Борис Васильевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Козлов Ярослав Семёнович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Михеев Платон Филиппович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Шестаков Аполлон Вячеславович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Щукин Илларион Гордеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Тарасов Елисей Кириллович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Маслов Юрий Федосеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Якушев Антон Макарович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Новиков Назарий Улебович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Громов Максим Максович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Устинов Геннадий Егорович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Котов Мартин Дмитриевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Игнатов Трофим Иванович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Петров Евгений Святославович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Воробьёв Варлаам Митрофанович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Прохоров Виссарион Кимович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Панов Пантелей Витальевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Бирюков Вениамин Аркадьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Петров Май Павлович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Давыдов Вилен Арсеньевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Анисимов Евгений Максович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Носков Ярослав Наумович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Никонов Андрей Александрович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Кузнецов Гаянэ Павлович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Лапин Трофим Валерьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Прохоров Степан Германнович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Виноградов Леонид Иринеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Мельников Даниил Мэлсович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Сидоров Мечеслав Филатович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Павлов Назарий Донатович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Симонов Антон Кириллович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Рожков Виссарион Павлович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Карпов Семен Тимофеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Туров Тарас Викторович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Копылов Савелий Федосеевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Кулаков Евдоким Богуславович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Сафонов Варлаам Антонович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Бобров Май Игнатьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Брагин Вилли Георгьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Большаков Рудольф Рубенович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Евсеев Федор Тарасович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Исаев Вячеслав Данилович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Тарасов Аввакум Германнович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Хохлов Роман Макарович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Суханов Василий Арсеньевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Артемьев Ян Игоревич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Цветков Григорий Валентинович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Медведев Даниил Артемович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Рожков Игорь Парфеньевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Мышкин Ермолай Богданович'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Бирюков Гордий Авксентьевич'); 
INSERT INTO [Managers] ([Name]) VALUES (N'Филатов Эрнест Владимирович'); 
--#endregion

--#region Добавление продуктов
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WinTools.net Premium 21.5.0 RePack (& portable) by KpoJIuK [Multi/Ru]', 170307, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'SketchUp Pro 2021 21.1.299 RePack by KpoJIuK [Ru/En]', 35744, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'MAGIX Video Pro X13 19.0.1.103 (x64) [Multi]', 2286, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WinTools.net Professional / Premium / Classic 21.5 RePack (& Portable) by Dodakaedr [Multi/Ru]', 287259, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Total Commander 10 final 64bit 32bit VIM 43 portable [Ru]', 213922, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'O&O BlueCon 18 Tech Edition Build 8088 WinPE Boot CD [En]', 36505, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Microsoft Office 2016-2019 Professional Plus / Standard + Visio + Project 16.0.14131.20278 (2021.06) (W10) RePack by KpoJIuK [Multi/Ru]', 274447, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Malwarebytes AdwCleaner 8.3.0.0 [Multi/Ru]', 240991, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'HiBit Uninstaller 2.6.15 + Portable [Multi/Ru]', 52575, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'4K Video Downloader 4.16.5.4310 RePack (& Portable) by TryRooM [Multi/Ru]', 173394, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WinTools.net Premium 21.5 RePack (& Portable) by TryRooM [Multi/Ru]', 107571, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMSAuto++ Portable by Ratiborus 01.07.2021 [Ru/En]', 194502, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera 77.0.4054.172 Portable by Cento8 [Ru/En]', 76661, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Ubuntu RescuePack v.21.06 (Antivirus LiveDisk) (июнь 2021) [Multi/Ru] (обновляемая раздача)', 149359, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Dr.Web CureIt! (29.06.2021) [Multi/Ru] (обновляемая раздача)', 59857, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Kaspersky Virus Removal Tool 20.0.6.0 (a) (29.06.2021) (обновляемая раздача)', 207455, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'JRiver Media Center 28.0.32 RePack (& Portable) by elchupacabra [Multi/Ru]', 184819, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Ant Download Manager Pro 2.3.0 Build 78861 RePack (& Portable) by xetrin [Multi/Ru]', 89653, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Mozilla FireFox 89.0.2.7843 Portable by JolyAnderson [Multi/Ru]', 223081, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera 77.0.4054.172 Portable by JolyAnderson [Multi/Ru]', 123356, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Spotify 1.1.62.583 Portable by JolyAnderson [En/Ru]', 46460, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'AllDup 4.4.56 + Portable [Multi/Ru]', 198601, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Aiseesoft Blu-ray Player 6.7.12 Repack (& Portable) by elchupacabra [Multi/Ru]', 239570, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Windows 10 (v21h1) x64 PRO by KulHunter v1.1 (esd) [En]', 56696, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'VueScan Pro 9.7.58 RePack (& Portable) by elchupacabra [Multi/Ru]', 287615, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Ashampoo Photo Card 2.0.4 DC (28.06.2021) RePack (& Portable) by elchupacabra [Multi/Ru]', 75517, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WhatsApp 2.2123.8 RePack (& Portable) by elchupacabra [Multi/Ru]', 276549, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'4K Video Downloader 4.16.5.4310 RePack (& Portable) by elchupacabra [Multi/Ru]', 179482, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Бизнес Пак 7.24 (сборка 4753) [Ru]', 95213, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'PrivaZer 4.0.26 RePack (& Portable) by elchupacabra [Multi/Ru]', 145240, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Vivaldi 4.0.2312.36 + Автономная версия (standalone) [Multi/Ru]', 79483, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'RogueKiller Anti-Malware 15.0.6 + Portable [Multi]', 282125, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'PureSync 7.0.1 [Multi/Ru]', 28850, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Topaz Video Enhance AI 2.3.0 RePack (& Portable) by TryRooM [En]', 26948, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Privacy Eraser Free 5.13.0 Build 3946 + Portable [Multi/Ru]', 67688, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'RAM Saver Professional 21.5 RePack (& Portable) by elchupacabra [Multi/Ru]', 242108, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'OCCT 8.2.3 Final Portable [Multi/Ru]', 144074, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMS Tools Portable by Ratiborus 01.07.2021 [Multi/Ru]', 73947, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMSAuto++ Portable 1.5.7 by Ratiborus [Ru/En]', 146631, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Comodo Dran 90.0.4430.212 + Portable [Multi/Ru]', 177871, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Slimjet 30.0.5.0 + Portable [Multi/Ru]', 262870, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Shotcut 21.06.29 + Portable [Multi/Ru]', 4271, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera GX 76.0.4017.220 + Portable [Multi/Ru]', 106987, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'MEmu 7.5.5 [Multi/Ru]', 195228, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Blackmagic Design DaVinci Resolve Studio 17.2.2 Build 4 [Multi/Ru]', 276749, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'O&O ShutUp10 1.8.1423.335 Portable [Multi/Ru]', 54512, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Windows 10 Manager 3.5.1.0 RePack (& Portable) by KpoJIuK [Multi/Ru]', 43922, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Acon Digital Collection 07.2021 VST, VST3, AAX (x86/x64) [En]', 250204, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'CorelDRAW Graphics Suite 2021 23.1.0.389 Portable by conservator [Ru/En]', 223769, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Honeyview 5.40 Build 5833 + Portable [Multi/Ru]', 123445, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Futuremark 3DMark 2.19.7225 Developer Edition RePack by KpoJIuK [Multi/Ru]', 276008, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Telegram Desktop 2.8.4 + Portable [Multi/Ru]', 270075, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'FontCreator Professional Edition 14.0.0.2794 RePack (& Portable) by elchupacabra [Ru/En]', 281092, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Blackmagic Design DaVinci Resolve Studio 17.2.2 Build 4 RePack by KpoJIuK [Multi/Ru]', 219890, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WinTools.net Premium 21.5 (2021) PC | RePack & Portable by Dodakaedr ', 166612, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'FontCreator Professional Edition 14.0.0.2794 (2021) PC | RePack & Portable by elchupacabra ', 263515, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Honeyview 5.40 Build 5833 (2021) PC | + Portable ', 274484, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Futuremark 3DMark 2.19.7225 Developer Edition (2021) PC | RePack by KpoJIuK ', 190965, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'CorelDRAW Graphics Suite 2021 23.1.0.389 (2021) PC | Portable by conservator ', 247188, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMSAuto++ 1.5.7 (2021) PC | Portable by Ratiborus ', 70157, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Vivaldi 4.0.2312.36 Stable (2021) PC | + Portable ', 263073, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Topaz Video Enhance AI 2.3.0 (2021) PC | RePack & Portable by TryRooM ', 21929, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Privacy Eraser Free 5.13.0 Build 3946 (2021) PC | + Portable ', 86366, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'RAM Saver Professional 21.5 (2021) PC | RePack & Portable by elchupacabra ', 22821, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'OCCT 8.2.3 (2021) PC | Portable ', 160930, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMS Tools [01.07.2021] (2021) PC | Portable by Ratiborus ', 83016, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera GX 76.0.4017.220 (2021) PC | + Portable ', 66530, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Shotcut 21.06.29 (2021) PC | + Portable ', 223086, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'MEmu 7.5.5 Final (2021) PC ', 163357, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Slimjet 30.0.5.0 (2021) PC | + Portable ', 73655, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Malwarebytes AdwCleaner 8.3.0.0 (2021) PC ', 8382, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'HiBit Uninstaller 2.6.15 (2021) PC | + Portable ', 292142, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'4K Video Downloader 4.16.5.4310 (2021) PC | RePack & Portable by TryRooM ', 203108, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'WinTools.net Premium 21.5 (2021) PC | RePack & Portable by TryRooM ', 238607, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'KMSAuto++ [01.07.2021] (2021) PC | Portable by Ratiborus ', 239108, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'O&O ShutUp10 1.8.1423.335 (2021) PC | Portable ', 4657, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Windows 10 Manager 3.5.1.0 (2021) PC | RePack & Portable by KpoJIuK ', 226379, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'SketchUp Pro 2021 21.1.299 (2021) РС | RePack by KpoJIuK ', 6810, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'FinePrint 10.45 + PdfFactory Pro 7.45 (2021) РС | RePack by elchupacabra ', 40763, N'Подписка', N'Квартал'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera 77.0.4054.172 (2021) РС | Portable by Cento8 ', 39379, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Calibre 5.22.1 (2021) PC | + Portable ', 106752, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Opera 77.0.4054.172 Stable (2021) РС ', 268053, N'Подписка', N'Год'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Ant Download Manager PRO 2.3.0 Build 78861 (2021) PC | RePack & Portable by xetrin ', 263052, N'Постоянная лицензия', NULL); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'JRiver Media Center 28.0.32 (2021) PC | RePack & Portable by elchupacabra ', 64123, N'Подписка', N'Месяц'); 
INSERT INTO [Products] ([Name], [Price], [Type], [SubscriptionPeriod]) VALUES (N'Aiseesoft Blu-ray Player 6.7.12 (2021) РС | RePack & Portable by elchupacabra ', 107704, N'Подписка', N'Квартал'); 
--#endregion

--#region Добавление клиентов
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЛОГИКА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РУСЬ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТАЙМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЭКОДОМ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Кузнецов Сергей Александрович', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТРОЙКА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ФЛАМИНГО"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАРГО"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СПЕЦИАЛИСТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ВИЛАР"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МЕГАТРАНС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "Даймонд"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "Мегалит"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИРИДА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЮНИТРЕЙД"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАТРИЦА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АГРОСНАБ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРОФАЛЬЯНС"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГАЛС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РЕГУЛ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ДЕКАРТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ВЕНЕЦИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КВАРТЕТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПЕРФЕКТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ФЕРРУМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "А-СТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СПЕКТРУМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЕНИСЕЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРАКТИК"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "БОСФОР"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПАМИР"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СЕМЬЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МИЛЯ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙКАПИТАЛ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СОЛЯРИС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СВЕТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАНУФАКТУРА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРОЕКТСТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТЕХИНВЕСТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРКТУР"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АЛЬФА СТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙАКТИВ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ФОКС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЭСТЕТИКА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙЛЮКС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СОВА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "Флекс"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "Талисман"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СПК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МЕТАЛЛСТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АКВА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАЛИБР"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРМСТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПАНТЕОН"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПОЛИМЕР"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АЛЬЯНС ПЛЮС"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГОЛЬФСТРИМ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙМАКС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "БРАВО"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПЛАТИНУМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МТК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АГРОПРОДУКТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРГОН"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИНТЕРА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "БОРЕЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИНТЕЛЛЕКТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРИНТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙТЕХНОЛОГИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТАЙФУН"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЭЛКОМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРОФТОРГ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СМАЙЛ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МОРИОН"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИНИЦИАТИВА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СЕВЕРНОЕ СИЯНИЕ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СМК"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТАЙГА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АВТОГРУЗ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙ ДОМ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАЛЕЙДОСКОП"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РУССТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЕВРОСТАНДАРТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙПЛЮС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ФАКТОРИЯ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЛЕСТОРГ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТЕХНИК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Попов Александр Владимирович', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАПИТАЛ СТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РАКЕТА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "БОНУС"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГЛАВСТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ВУЛКАН"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙОПТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СИБТОРГ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РЕНОВАЦИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РОМАШКА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГЕПАРД"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МЯТА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТЕПЛЫЙ ДОМ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЧИСТЫЙ ДОМ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАПИТАЛ ГРУПП"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Иванов Андрей Владимирович', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАЛИНА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АБРИС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРИАДНА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПРОМТЕХСНАБ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АВТОЛИГА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АТЛАНТИДА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТАНТАЛ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Иванов Андрей Александрович', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЭПСИЛОН"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТЕХНОПОЛИС"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КОНСТРУКТИВ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АСТАРТА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИНТЕГРАЦИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АРТВЭЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "М-СТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ПЕРСОНА"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СТРОЙКОМФОРТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Иванов Дмитрий Сергеевич', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СОФИТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГЕОМЕТРИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГАЛАТЕЯ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ВЕРА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РЕЗУЛЬТАТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Кузнецов Алексей Владимирович', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ВЕКТОР-М"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИНЖЕНЕРНЫЕ РЕШЕНИЯ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РИТЕЙЛ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАРИЯ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАРИС"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "БАРАКАТ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "Строй Плюс"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СЕРВИССТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ФРЕШ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ИКАР"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ТЕХАЛЬЯНС"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЗДОРОВЬЕ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ГАРАНТ-СТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АВИТЕК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "СОГЛАСИЕ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КАСПИЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Иванова Елена Александровна', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАТЕРИК"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЧИСТЫЙ ГОРОД"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЕВА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЛАДА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "АВТОПРОФИ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "РЕГАТА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КОМСТРОЙ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МЕГАТРЕЙД"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "КСК"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАГМА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МИЛЕНА"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ИП Попов Сергей Александрович', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ЛОГИСТ"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "ОРИЕНТИР"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "УНИВЕРСАЛСТРОЙ"', '0', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
INSERT INTO [Clients] ([Name], [Status], [ManagerId]) VALUES (N'ООО "МАНДАРИН"', '1', (SELECT TOP 1 Id FROM Managers ORDER BY NEWID())); 
--#endregion

--#region Добавление продуктов клиентам
DECLARE @i INT, @randomClientId INT, @randomProductId INT
SET @i = 2000;
 
WHILE @i > 0
    BEGIN
		SET @randomClientId = (SELECT TOP 1 Id FROM Clients ORDER BY NEWID())
		SET @randomProductId = (SELECT TOP 1 Id FROM Products ORDER BY NEWID())
		IF ((select count(1)
			 from ClientProduct
		     where ClientsId = @randomClientId and ProductsId = @randomProductId) = 0)
			 BEGIN
				INSERT INTO [ClientProduct] ([ClientsId], [ProductsId]) 
				VALUES (@randomClientId, @randomProductId); 
				SET @i = @i - 1
			 END;
		ELSE
			CONTINUE;
    END;
--#endregion